import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {MapPin,Truck,Package,CalendarDays,Clock,Phone,ShieldCheck,ArrowRight,LogOut,LayoutDashboard,ClipboardList,CheckCircle,XCircle,Menu} from "lucide-react";
import "./styles.css";

const API="http://localhost:5000/api";
const getToken=()=>localStorage.getItem("rjm_token");
async function api(path,opts={}){const r=await fetch(API+path,{...opts,headers:{"Content-Type":"application/json",...(opts.headers||{}),...(getToken()?{Authorization:"Bearer "+getToken()}: {})}});const d=await r.json();if(!r.ok)throw Error(d.message||"Request failed");return d}

function App(){
 const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem("rjm_user")||"null"));
 const [page,setPage]=useState("home");
 const [menu,setMenu]=useState(false);
 const login=u=>{setUser(u);setPage(u.role==="admin"?"admin":"book");setMenu(false)};
 const logout=()=>{localStorage.clear();setUser(null);setPage("home")};
 return <><header><div className="brand"><div className="logo"><Truck size={23}/></div><span>RJM <b>Transport</b></span></div><button className="mobile" onClick={()=>setMenu(!menu)}><Menu/></button><nav className={menu?"open":""}>
 <button onClick={()=>setPage("home")}>Home</button><button onClick={()=>setPage("services")}>Services</button>
 {user&&<button onClick={()=>setPage(user.role==="admin"?"admin":"mybookings")}>{user.role==="admin"?"Admin Dashboard":"My Bookings"}</button>}
 {!user?<><button className="outline" onClick={()=>setPage("login")}>Login</button><button className="primary small" onClick={()=>setPage("register")}>Register</button></>:<button className="outline" onClick={logout}><LogOut size={16}/> Logout</button>}
 </nav></header>
 {page==="home"&&<Home setPage={setPage}/>}
 {page==="services"&&<Services setPage={setPage}/>}
 {page==="login"&&<Auth mode="login" onLogin={login} go={setPage}/>}
 {page==="register"&&<Auth mode="register" onLogin={login} go={setPage}/>}
 {page==="book"&&<Booking user={user} go={setPage}/>}
 {page==="mybookings"&&<MyBookings/>}
 {page==="admin"&&user?.role==="admin"&&<Admin/>}
 <footer>© 2026 RJM Transport · Reliable courier & logistics services</footer>
 </>;
}

function Home({setPage}){return <main><section className="hero"><div className="heroText"><span className="eyebrow">FAST • SAFE • ON TIME</span><h1>Your parcel.<br/><span>Our responsibility.</span></h1><p>Book trusted courier transportation with RJM Transport. Schedule pickups in advance and track every booking from one simple dashboard.</p><div><button className="primary" onClick={()=>setPage("book")}>Book a Courier <ArrowRight size={18}/></button><button className="ghost" onClick={()=>setPage("services")}>Explore Services</button></div></div><div className="heroCard"><Truck size={70}/><b>RJM EXPRESS</b><span>Door-to-door delivery</span><div className="route"><MapPin/> Pickup <ArrowRight/> Drop</div></div></section><section className="features"><Feature icon={<Truck/>} title="Reliable Transport" text="Professional pickup and delivery."/><Feature icon={<CalendarDays/>} title="Pre-Booking" text="Choose your preferred date & time."/><Feature icon={<ShieldCheck/>} title="Admin Approval" text="Every booking is verified."/><Feature icon={<Phone/>} title="Easy Support" text="Get help when you need it." /></section></main>}
function Feature({icon,title,text}){return <div className="feature"><div className="icon">{icon}</div><h3>{title}</h3><p>{text}</p></div>}
function Services({setPage}){return <main className="container"><div className="pageTitle"><span className="eyebrow">RJМ TRANSPORT</span><h2>Courier services built for your business</h2><p>From documents to larger parcels, choose the service that fits your delivery.</p></div><div className="serviceGrid">{["Same-Day Courier","Scheduled Delivery","Business Logistics","Bulk Parcel Transport"].map((x,i)=><div className="service" key={x}><Package/><h3>{x}</h3><p>{["Fast local pickup and delivery.","Pre-book a date and time in advance.","Reliable recurring delivery support.","Move multiple packages with ease."][i]}</p><button className="linkBtn" onClick={()=>setPage("book")}>Book now →</button></div>)}</div></main>}
function Auth({mode,onLogin,go}){const [f,setF]=useState({});const [err,setErr]=useState("");const submit=async e=>{e.preventDefault();setErr("");try{const d=await api("/auth/"+mode,{method:"POST",body:JSON.stringify(f)});localStorage.setItem("rjm_token",d.token);localStorage.setItem("rjm_user",JSON.stringify(d.user));onLogin(d.user)}catch(e){setErr(e.message)}};return <main className="authWrap"><form className="auth" onSubmit={submit}><div className="logo big"><Truck/></div><h2>{mode==="login"?"Welcome back":"Create your RJM account"}</h2><p>{mode==="login"?"Login to manage your courier bookings.":"Register to schedule your courier pickup."}</p>{mode==="register"&&<input placeholder="Full name" required onChange={e=>setF({...f,name:e.target.value})}/>}<input placeholder="Mobile number" required onChange={e=>setF({...f,mobile:e.target.value})}/>{mode==="register"&&<input placeholder="Address" onChange={e=>setF({...f,address:e.target.value})}/>}<input type="password" placeholder="Password" required onChange={e=>setF({...f,password:e.target.value})}/>{err&&<div className="error">{err}</div>}<button className="primary full">{mode==="login"?"Login":"Register"}</button><p className="switch">{mode==="login"?"New to RJM? ":"Already registered? "}<button type="button" onClick={()=>go(mode==="login"?"register":"login")}>{mode==="login"?"Register":"Login"}</button></p></form></main>}

function Booking({user,go}){const [f,setF]=useState({service_type:"Same-Day Courier"});const [msg,setMsg]=useState("");if(!user)return <main className="authWrap"><div className="auth"><h2>Login required</h2><p>Please login before creating a booking.</p><button className="primary full" onClick={()=>go("login")}>Login</button></div></main>;const submit=async e=>{e.preventDefault();try{await api("/bookings",{method:"POST",body:JSON.stringify(f)});setMsg("Booking submitted successfully. RJM admin will review it.");setF({service_type:"Same-Day Courier"})}catch(e){setMsg(e.message)}};return <main className="container bookingPage"><div className="pageTitle"><span className="eyebrow">PRE-BOOKING</span><h2>Book a courier pickup</h2><p>Enter your delivery details. Your booking becomes active after admin acceptance.</p></div><div className="bookingGrid"><form className="panel form" onSubmit={submit}><label>Service Type<select value={f.service_type||""} onChange={e=>setF({...f,service_type:e.target.value})}><option>Same-Day Courier</option><option>Scheduled Delivery</option><option>Business Logistics</option><option>Bulk Parcel Transport</option></select></label><div className="two"><label>Pickup location<input required value={f.pickup||""} onChange={e=>setF({...f,pickup:e.target.value})}/></label><label>Drop location<input required value={f.dropoff||""} onChange={e=>setF({...f,dropoff:e.target.value})}/></label></div><div className="two"><label>Date<input type="date" required value={f.date||""} onChange={e=>setF({...f,date:e.target.value})}/></label><label>Pickup time<input type="time" required value={f.time||""} onChange={e=>setF({...f,time:e.target.value})}/></label></div><label>Package details<input placeholder="e.g. documents, 2 kg parcel" value={f.package_details||""} onChange={e=>setF({...f,package_details:e.target.value})}/></label><label>Additional notes<textarea value={f.notes||""} onChange={e=>setF({...f,notes:e.target.value})}/></label>{msg&&<div className="success">{msg}</div>}<button className="primary full"><CalendarDays size={18}/> Submit Pre-Booking</button></form><aside className="panel summary"><h3>Booking summary</h3><p><Phone/> {user.mobile}</p><p><MapPin/> {user.address||"Address saved to profile"}</p><p><Clock/> {f.date||"Select date"} · {f.time||"Select time"}</p><div className="notice"><ShieldCheck/> Admin approval is required before dispatch.</div></aside></div></main>}

function MyBookings(){const [rows,setRows]=useState([]);useEffect(()=>{api("/bookings").then(setRows).catch(()=>{})},[]);return <main className="container"><div className="pageTitle"><h2>My Bookings</h2><p>View your courier requests and their approval status.</p></div><BookingTable rows={rows}/></main>}
function Admin(){const [stats,setStats]=useState({});const [rows,setRows]=useState([]);const load=()=>Promise.all([api("/admin/stats"),api("/bookings")]).then(([s,b])=>{setStats(s);setRows(b)});useEffect(()=>{load()},[]);const status=async(id,s)=>{await api("/bookings/"+id+"/status",{method:"PATCH",body:JSON.stringify({status:s})});load()};return <main className="container"><div className="pageTitle"><span className="eyebrow">ADMIN PANEL</span><h2>RJM Transport Dashboard</h2><p>Review customer details and approve or reject courier bookings.</p></div><div className="stats"><Stat n={stats.total} t="Total bookings"/><Stat n={stats.pending} t="Pending approval"/><Stat n={stats.accepted} t="Accepted"/><Stat n={stats.users} t="Registered users"/></div><div className="panel tablePanel"><div className="tableHead"><h3>Booking requests</h3><span>Customer mobile, address, pickup and schedule</span></div><BookingTable rows={rows} admin status={status}/></div></main>}
function Stat({n,t}){return <div className="stat"><span>{n||0}</span><small>{t}</small></div>}
function BookingTable({rows,admin,status}){return <div className="tableScroll"><table><thead><tr><th>#</th><th>Customer</th><th>Mobile</th><th>Pickup → Drop</th><th>Date & Time</th><th>Service</th><th>Status</th>{admin&&<th>Action</th>}</tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td>{r.id}</td><td><b>{r.name}</b><br/><small>{r.address}</small></td><td>{r.mobile}</td><td>{r.pickup}<br/>→ {r.dropoff}</td><td>{r.date}<br/>{r.time}</td><td>{r.service_type}</td><td><span className={"badge "+r.status.toLowerCase()}>{r.status}</span></td>{admin&&<td>{r.status==="Pending"?<div className="actions"><button className="accept" onClick={()=>status(r.id,"Accepted")}><CheckCircle size={15}/> Accept</button><button className="reject" onClick={()=>status(r.id,"Rejected")}><XCircle size={15}/> Reject</button></div>:<button className="mini" onClick={()=>status(r.id,"Completed")}>Mark completed</button>}</td>}</tr>):<tr><td colSpan={admin?8:7} className="empty">No bookings yet.</td></tr>}</tbody></table></div>}

createRoot(document.getElementById("root")).render(<App/>);